export const customersDataTest = [
  {
    "id": 79897,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Carlos",
    "maternalSurname": "",
    "paternalSurname": "franco",
    "rfc": "",
    "street": "Allende ",
    "interiorNumber": "sur",
    "exteriorNumber": "15",
    "postalCode": "81200",
    "phone": "6681130709",
    "city": "los mochis",
    "municipality": "los mochis",
    "neighborhood": "Centro",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": false,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Carlos",
    "completeAddress": "Allende   Centro, los mochis, Sinaloa, 81200, MX",
    "isNaturalPerson": true,
    "hasErrors": true
  },
  {
    "id": 79989,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Carlos",
    "maternalSurname": "",
    "paternalSurname": "Franco",
    "rfc": "XAXX010101000",
    "street": "Principal",
    "interiorNumber": "",
    "exteriorNumber": "15",
    "postalCode": "6200000",
    "phone": "6681130709",
    "city": "punta arenas",
    "municipality": "magallanes",
    "neighborhood": "punta arenas",
    "email": "cfranco@pktuno.com",
    "addressType": "fiscal",
    "registrationDate": "12/02/2022 12:00:00 a. m.",
    "credit": "No",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "CL",
    "state": "magallanes y de la antartica chilena",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 37,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Carlos",
    "completeAddress": "Principal  punta arenas, punta arenas, magallanes y de la antartica chilena, 6200000, CL",
    "isNaturalPerson": true,
    "hasErrors": true
  },
  {
    "id": 80896,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Carlos",
    "maternalSurname": "",
    "paternalSurname": "Franco",
    "rfc": "",
    "street": "ppal ",
    "interiorNumber": "",
    "exteriorNumber": "15",
    "postalCode": "80000",
    "phone": "6681130709",
    "city": "Culiacan",
    "municipality": "Culiacan",
    "neighborhood": "Centro",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Carlos",
    "completeAddress": "ppal   Centro, Culiacan, Sinaloa, 80000, MX",
    "isNaturalPerson": true,
    "hasErrors": false
  },
  {
    "id": 80900,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Carlos",
    "maternalSurname": "",
    "paternalSurname": "Franco",
    "rfc": "XAXX010101000",
    "street": "ppal ",
    "interiorNumber": "12",
    "exteriorNumber": "15",
    "postalCode": "22000",
    "phone": "6681130709",
    "city": "Tijuana",
    "municipality": "Tijuana",
    "neighborhood": "Zona Centro",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": false,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Baja California",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Carlos",
    "completeAddress": "ppal   Zona Centro, Tijuana, Baja California, 22000, MX",
    "isNaturalPerson": true,
    "hasErrors": true
  },
  {
    "id": 81065,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "sfgff",
    "maternalSurname": "",
    "paternalSurname": "gdfg",
    "rfc": "XAXX010101000",
    "street": "vgdf",
    "interiorNumber": "",
    "exteriorNumber": "345",
    "postalCode": "81290",
    "phone": "5446341",
    "city": "Los Mochis",
    "municipality": "Ahome",
    "neighborhood": "Morelos",
    "email": "fvgfdsdjsfcsdl@dfsd.com",
    "addressType": "fiscal",
    "registrationDate": "23/02/2022 12:00:00 a. m.",
    "credit": "No",
    "check": "",
    "isActive": false,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 37,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "sfgff",
    "completeAddress": "vgdf  Morelos, Los Mochis, Sinaloa, 81290, MX",
    "isNaturalPerson": true,
    "hasErrors": true
  },
  {
    "id": 81533,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "fher",
    "maternalSurname": "",
    "paternalSurname": "valenzuela",
    "rfc": "XAXX010101000",
    "street": "morelos",
    "interiorNumber": "",
    "exteriorNumber": "1908",
    "postalCode": "81290",
    "phone": "1538561351352",
    "city": "Los Mochis",
    "municipality": "Ahome",
    "neighborhood": "Morelos",
    "email": "fherne@hotm.com",
    "addressType": "fiscal",
    "registrationDate": "01/03/2022 12:00:00 a. m.",
    "credit": "No",
    "check": "",
    "isActive": false,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 37,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "fher",
    "completeAddress": "morelos  Morelos, Los Mochis, Sinaloa, 81290, MX",
    "isNaturalPerson": true,
    "hasErrors": false
  },
  {
    "id": 82002,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Juana",
    "maternalSurname": "",
    "paternalSurname": "De Arco",
    "rfc": "XAXX010101000",
    "street": "Insurgentes s/n",
    "interiorNumber": "INT 15",
    "exteriorNumber": "0",
    "postalCode": "06600",
    "phone": "6681130009",
    "city": "Ciudad de Mexico",
    "municipality": "Cuauhtemoc",
    "neighborhood": "Juarez",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Ciudad de Mexico",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Juana",
    "completeAddress": "Insurgentes s/n  Juarez, Ciudad de Mexico, Ciudad de Mexico, 06600, MX",
    "isNaturalPerson": true,
    "hasErrors": true
  },
  {
    "id": 82004,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Ricardo",
    "maternalSurname": "",
    "paternalSurname": "Cortez",
    "rfc": "XAXX010101000",
    "street": "Rio fuerte ",
    "interiorNumber": "",
    "exteriorNumber": "15",
    "postalCode": "82000",
    "phone": "6681130709",
    "city": "Mazatlan",
    "municipality": "Mazatlan",
    "neighborhood": "Los Pinos",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Ricardo",
    "completeAddress": "Rio fuerte   Los Pinos, Mazatlan, Sinaloa, 82000, MX",
    "isNaturalPerson": true,
    "hasErrors": false
  },
  {
    "id": 82005,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Julio",
    "maternalSurname": "",
    "paternalSurname": "Regalado",
    "rfc": "XAXX010101000",
    "street": "Rio fuerte ",
    "interiorNumber": "",
    "exteriorNumber": "15",
    "postalCode": "82100",
    "phone": "6681130709",
    "city": "Mazatlan",
    "municipality": "Mazatlan",
    "neighborhood": "Sabalo Country Club",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Julio",
    "completeAddress": "Rio fuerte   Sabalo Country Club, Mazatlan, Sinaloa, 82100, MX",
    "isNaturalPerson": true,
    "hasErrors": false
  },
  {
    "id": 82006,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Jakeline",
    "maternalSurname": "",
    "paternalSurname": "Andrade",
    "rfc": "XAXX010101000",
    "street": "Rio fuerte ",
    "interiorNumber": "",
    "exteriorNumber": "15",
    "postalCode": "82100",
    "phone": "6681130709",
    "city": "Mazatlan",
    "municipality": "Mazatlan",
    "neighborhood": "Sabalo Country Club",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Jakeline",
    "completeAddress": "Rio fuerte   Sabalo Country Club, Mazatlan, Sinaloa, 82100, MX",
    "isNaturalPerson": true,
    "hasErrors": false
  },
  {
    "id": 82060,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Juana",
    "maternalSurname": "",
    "paternalSurname": "De Arco",
    "rfc": "XAXX010101000",
    "street": "Insurgentes s/n",
    "interiorNumber": "0",
    "exteriorNumber": "20",
    "postalCode": "06600",
    "phone": "6681130709",
    "city": "Ciudad de Mexico",
    "municipality": "Cuauhtemoc",
    "neighborhood": "Juarez",
    "email": "cfranco@pktuno.com",
    "addressType": "Fiscal",
    "registrationDate": "",
    "credit": "",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Ciudad de Mexico",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 0,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Juana",
    "completeAddress": "Insurgentes s/n  Juarez, Ciudad de Mexico, Ciudad de Mexico, 06600, MX",
    "isNaturalPerson": true,
    "hasErrors": true
  },
  {
    "id": 82787,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Ernesto",
    "maternalSurname": "Soto",
    "paternalSurname": "Sanchez ",
    "rfc": "XAXX010101000",
    "street": "calle 7",
    "interiorNumber": "1",
    "exteriorNumber": "74",
    "postalCode": "80000",
    "phone": "6682652149",
    "city": "Culiacan Rosales",
    "municipality": "Culiacan",
    "neighborhood": "Centro",
    "email": "ernesto.soto.1998@hotmail.com",
    "addressType": "fiscal",
    "registrationDate": "12/03/2022 12:00:00 a. m.",
    "credit": "No",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 37,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Ernesto Sanchez  Soto",
    "completeAddress": "calle 7  Centro, Culiacan Rosales, Sinaloa, 80000, MX",
    "isNaturalPerson": true,
    "hasErrors": false
  },
  {
    "id": 82788,
    "internalCode": "",
    "type": "Fisica",
    "firstName": "Juan",
    "maternalSurname": "",
    "paternalSurname": "Luna",
    "rfc": "XAXX010101000",
    "street": "calle 7",
    "interiorNumber": "1",
    "exteriorNumber": "74",
    "postalCode": "80000",
    "phone": "6682652148",
    "city": "Culiacan Rosales",
    "municipality": "Culiacan",
    "neighborhood": "Centro",
    "email": "juan@gmail.com",
    "addressType": "fiscal",
    "registrationDate": "12/03/2022 12:00:00 a. m.",
    "credit": "No",
    "check": "",
    "isActive": true,
    "comments": "",
    "franchiseId": 1,
    "franchiseName": null,
    "country": "MX",
    "state": "Sinaloa",
    "creditAmount": 0,
    "paymentDay": 0,
    "reviewDay": 0,
    "receiptType": "",
    "biweeklyBilling": "No",
    "viewShipments": 0,
    "gender": "",
    "age": 0,
    "businessType": 37,
    "clientOSId": 6212,
    "advisorId": 0,
    "printer": 0,
    "satKey": 31181701,
    "keyVal": null,
    "fullName": "Juan",
    "completeAddress": "calle 7  Centro, Culiacan Rosales, Sinaloa, 80000, MX",
    "isNaturalPerson": true,
    "hasErrors": true
  }
]